In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('laptops.csv')
data.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [4]:
## Normalize the column names
data.columns = data.columns.str.replace(' ','_').str.lower()
data.head()

laptop status   brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        model            cpu  ram  storage storage_type       gpu  screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  touch  final_price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

Next, use only the following columns:

'ram',
'storage',
'screen',
'final_price'

In [5]:
col_list = ['ram','storage','screen','final_price']
df = data[col_list]
df.head()

ram  storage  screen  final_price
0    8      512    15.6      1009.00
1    8      256    15.6       299.00
2    8      256    15.6       789.00
3   16     1000    15.6      1199.00
4   16      512    15.6       669.01

### Q1. Which column has missing values?


In [6]:
df.ram.isnull().sum()
## 0

np.int64(0)

In [7]:
df.storage.isnull().sum()
## 0

np.int64(0)

In [8]:
df.screen.isnull().sum()
## 4

np.int64(4)

In [9]:
df.final_price.isnull().sum()
## 0

np.int64(0)

### A1: 'Screen' has missing values

### Q2: What's the median (50% percentile) for variable 'ram'?

8, 
16, 
24, 
32, 

In [10]:
df.describe()

ram      storage       screen  final_price
count  2160.000000  2160.000000  2156.000000  2160.000000
mean     15.413889   596.294444    15.168112  1312.638509
std       9.867815   361.220506     1.203329   911.475417
min       4.000000     0.000000    10.100000   201.050000
25%       8.000000   256.000000    14.000000   661.082500
50%      16.000000   512.000000    15.600000  1031.945000
75%      16.000000  1000.000000    15.600000  1708.970000
max     128.000000  4000.000000    18.000000  7150.470000

### A2: Median RAM: 16

## Prepare and split the dataset
- Shuffle the dataset (the filtered one you created above), use seed 42.
- Split your data in train/val/test sets, with 60%/20%/20% distribution.
Use the same code as in the lectures

In [11]:
### shuffle with seed 42
import random
shuffled_df = df.sample(frac=1, random_state=42).reset_index(drop=True)
shuffled_df

ram  storage  screen  final_price
0      32     1000    15.6      1123.29
1       4       64    14.1       201.05
2      32     1000    14.0       997.74
3      16      512    13.3      1016.00
4      32     1000    16.0      2739.00
...   ...      ...     ...          ...
2155    8      512    15.0      1838.29
2156    8      256    15.6       531.80
2157    8      256    13.3       765.33
2158    8      512    14.0       803.61
2159   32     1000    16.0      2102.18

[2160 rows x 4 columns]

In [12]:
### Split the data into train/val/test
from sklearn.model_selection import train_test_split
df_full_train, df_test = train_test_split(shuffled_df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)



#### Question 3
- We need to deal with missing values for the column from Q1.
- We have two options: fill it with 0 or with the mean of this variable.
- Try both options. For each, train a linear regression model without regularization using the code from the lessons.
- For computing the mean, use the training only!
- Use the validation dataset to evaluate the models and compare the RMSE of each option.
- Round the RMSE scores to 2 decimal digits using round(score, 2)
- Which option gives better RMSE?
Options:

- With 0
- With mean
- Both are equally good

#### Case 1: Missing with 0

In [37]:
shuffled_df_na_zero = shuffled_df.fillna(0)
shuffled_df_na_zero.screen.isnull().sum()

np.int64(0)

In [38]:
### Split the data into train/val/test
from sklearn.model_selection import train_test_split
df_full_train, df_test = train_test_split(shuffled_df_na_zero, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

### Extract the target vector
y_train = df_train.final_price.values
y_val = df_val.final_price.values
y_test = df_test.final_price.values

### remove target column from datasets to avoid accidental usage
del df_train['final_price']
del df_val['final_price']
del df_test['final_price']

In [39]:
### reset the index
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [40]:
X_train = df_train.values
X_train

array([[  8. , 256. ,  13. ],
       [  8. , 512. ,  15.6],
       [  8. ,  64. ,  17.3],
       ...,
       [ 16. , 512. ,  15.6],
       [  8. , 512. ,  15.6],
       [ 16. , 512. ,  14. ]], shape=(1296, 3))

In [41]:
X_val = df_val.values
X_test = df_test.values

In [42]:
from sklearn.linear_model import LinearRegression
### Train the Linear Regression
lr_na_zero = LinearRegression()
lr_na_zero.fit(X_train, y_train)
y_pred = lr_na_zero.predict(X_val)
y_pred

array([ 671.79972671, 1777.09759824, 1252.42819037, 1729.73645555,
        766.5220121 , 1771.17745541, 1777.09759824, 1794.85802675,
       1240.69110189,  731.00115508, 4638.92940427, 1252.42819037,
       1320.509833  , 1797.81809817,  922.19094779, 1777.09759824,
       1252.42819037, 1729.73645555,  703.51141809, 1252.42819037,
       1299.78933307,  922.19094779, 1714.19933166,  499.88835162,
       1729.73645555,  381.48549488, 2390.21094072,  719.16086941,
       1299.78933307, 1679.41524143,  922.19094779,  922.19094779,
        671.79972671,  671.79972671, 1299.78933307,  969.55209048,
       1252.42819037, 2339.8897266 , 1777.09759824,  922.19094779,
        969.55209048,  969.55209048, 1317.54976158, 1252.42819037,
       2339.8897266 , 1299.78933307,  671.79972671, 2378.37065504,
        922.19094779,  405.99164372,  922.19094779, 1299.78933307,
        957.815002  ,  922.19094779, 1729.73645555, 1729.73645555,
       2437.57208341, 1252.42819037, 2348.76994086, 2390.21094

In [ ]:
### RMSE of Validation vs Training
from sklearn.metrics import mean_squared_error
rmse_lr_na_zero = round(np.sqrt(mean_squared_error(y_val, y_pred)),2)
rmse_lr_na_zero
### 616.83

np.float64(616.83)

### Case 2: Mean of Training

In [27]:
### Split the data into train/val/test
from sklearn.model_selection import train_test_split
df_full_train, df_test = train_test_split(shuffled_df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

### Extract the target vector
y_train = df_train.final_price.values
y_val = df_val.final_price.values
y_test = df_test.final_price.values

### remove target column from datasets to avoid accidental usage
del df_train['final_price']
del df_val['final_price']
del df_test['final_price']

### reset the index
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [28]:
### Count missing Screen in each df 
from IPython.display import display

display(df_train.screen.isnull().sum()) 
display(df_val.screen.isnull().sum())
display(df_test.screen.isnull().sum())

np.int64(2)

np.int64(1)

np.int64(1)

In [29]:
screen_mean = df_train.screen.mean()
screen_mean

np.float64(15.179598145285937)

In [30]:
df_train.screen = df_train.screen.fillna(screen_mean)
df_val.screen = df_val.screen.fillna(screen_mean)
df_test.screen = df_test.screen.fillna(screen_mean)

In [31]:
### Check if there are any missing Screen in each df 
from IPython.display import display

display(df_train.screen.isnull().sum()) 
display(df_val.screen.isnull().sum())
display(df_test.screen.isnull().sum())

np.int64(0)

np.int64(0)

np.int64(0)

In [32]:
### Extract the Feature Matrices
X_train = df_train.values
X_val = df_val.values
X_test = df_test.values

In [33]:
from sklearn.linear_model import LinearRegression
### Train the Linear Regression
lr_na_mean = LinearRegression()
lr_na_mean.fit(X_train, y_train)
y_pred = lr_na_mean.predict(X_val)
y_pred

array([ 675.09713469, 1773.06972761, 1254.51071281, 1729.8097131 ,
        761.61716371, 1767.66222579, 1773.06972761, 1789.29223305,
       1242.82303248,  729.17215283, 4638.27769479, 1254.51071281,
       1316.69698367, 1791.99598396,  924.43431517, 1773.06972761,
       1254.51071281, 1729.8097131 ,  702.77357542, 1254.51071281,
       1297.77072732,  924.43431517, 1265.87733177,  493.54038191,
       1729.8097131 ,  385.39034563, 2389.96250839,  718.3571492 ,
       1297.77072732, 1683.84594768,  924.43431517,  924.43431517,
        675.09713469,  675.09713469, 1297.77072732,  967.69432968,
       1254.51071281, 2343.99874297, 1773.06972761,  924.43431517,
        967.69432968,  967.69432968, 1313.99323277, 1254.51071281,
       2343.99874297, 1297.77072732,  675.09713469, 2379.14750476,
        924.43431517,  400.03893923,  924.43431517, 1297.77072732,
        956.00664934,  924.43431517, 1729.8097131 , 1729.8097131 ,
       2433.2225229 , 1254.51071281, 2352.10999569, 2389.96250

In [ ]:
### RMSE of Validation vs Training
from sklearn.metrics import mean_squared_error
rmse_lr_na_mean = round(np.sqrt(mean_squared_error(y_val, y_pred)),2)
rmse_lr_na_mean
### 617.13

np.float64(617.13)

### A3: With 0, RMSE is better

### Question 4
- Now let's train a regularized linear regression.
- For this question, fill the NAs with 0.
- Try different values of r from this list: [0, 0.01, 0.1, 1, 5, 10, 100].
- Use RMSE to evaluate the model on the validation dataset.
- Round the RMSE scores to 2 decimal digits.
- Which r gives the best RMSE?
- If there are multiple options, select the smallest r.

Options:

- 0
- 0.01
- 1
- 10
- 100

In [44]:
shuffled_df_na_zero = shuffled_df.fillna(0)
shuffled_df_na_zero.screen.isnull().sum()

np.int64(0)

In [45]:
### Split the data into train/val/test
from sklearn.model_selection import train_test_split
df_full_train, df_test = train_test_split(shuffled_df_na_zero, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

### Extract the target vector
y_train = df_train.final_price.values
y_val = df_val.final_price.values
y_test = df_test.final_price.values

### remove target column from datasets to avoid accidental usage
del df_train['final_price']
del df_val['final_price']
del df_test['final_price']

### reset the index
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [46]:
### Extract the Feature Matrices
X_train = df_train.values
X_val = df_val.values
X_test = df_test.values

In [49]:
from sklearn.linear_model import Ridge
### Train the Ridge Regression
rr_na_zero = Ridge(alpha=0)
rr_na_zero.fit(X_train, y_train)
y_pred = rr_na_zero.predict(X_val)
y_pred

array([ 671.79972671, 1777.09759824, 1252.42819037, 1729.73645555,
        766.5220121 , 1771.17745541, 1777.09759824, 1794.85802675,
       1240.69110189,  731.00115508, 4638.92940427, 1252.42819037,
       1320.509833  , 1797.81809817,  922.19094779, 1777.09759824,
       1252.42819037, 1729.73645555,  703.51141809, 1252.42819037,
       1299.78933307,  922.19094779, 1714.19933166,  499.88835162,
       1729.73645555,  381.48549488, 2390.21094072,  719.16086941,
       1299.78933307, 1679.41524143,  922.19094779,  922.19094779,
        671.79972671,  671.79972671, 1299.78933307,  969.55209048,
       1252.42819037, 2339.8897266 , 1777.09759824,  922.19094779,
        969.55209048,  969.55209048, 1317.54976158, 1252.42819037,
       2339.8897266 , 1299.78933307,  671.79972671, 2378.37065504,
        922.19094779,  405.99164372,  922.19094779, 1299.78933307,
        957.815002  ,  922.19094779, 1729.73645555, 1729.73645555,
       2437.57208341, 1252.42819037, 2348.76994086, 2390.21094

In [50]:
### RMSE of Validation vs Training
from sklearn.metrics import mean_squared_error
rmse_rr_na_zero = round(np.sqrt(mean_squared_error(y_val, y_pred)),2)
rmse_rr_na_zero
### 616.83

np.float64(616.83)

In [56]:
r = [0, 0.01, 0.1, 1, 5, 10, 100]

rmse_scores = {}

for reg in r:
    rr_na_zero = Ridge(alpha=reg)
    rr_na_zero.fit(X_train, y_train)
    y_pred = rr_na_zero.predict(X_val)
    rmse_rr_na_zero = round(np.sqrt(mean_squared_error(y_val, y_pred)),2)
    rmse_scores[reg] = rmse_rr_na_zero

rmse_scores


{0: np.float64(616.83),
 0.01: np.float64(616.83),
 0.1: np.float64(616.83),
 1: np.float64(616.83),
 5: np.float64(616.84),
 10: np.float64(616.84),
 100: np.float64(616.98)}